### ISSUE TITLE
Accessing UserResource simply give 404

### ISSUE THREAD

**Issue by rabol** [nebulapackage/nebula#56]
Hi

Just tried to install Nebula using the the instructions: https://nebulapackage.com/installation

I then created a new 'UserResource'
Registered the resource in the config file

http://test.test/nebula/resources/users

simply return 404

**Comment by Larsklopstra** [comment]
Not enough info. Please re-open the issue if you have a repository available or more information

**Comment by johnpuddephatt** [comment]
Same here – was an auth issue, switching to email based auth solved it. (on a side note I'm not sure why the default 127.0.0.1 in allowed_ips wasn't allowing me in as I'm on my local machine but I'll look into that separately).

Wasn't immediately obvious because I could access /nebula but not /nebula/resources/users

Posting this in case anyone else experiences the same problem.
